version: '3.8'

services:
  # Backend service (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - backend_data:/app/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service (Flutter Web)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  backend_data: 